require("core.options")
require("core.keymaps")
require("core.neovide")
require("core.lsp")

require("plugins.util")
require("plugins.themes")
require("plugins.blink")
require("plugins.render-markdown")
require("plugins.ai")
require("plugins.snacks")
require("plugins.git")
require("plugins.conform")
